version: '3.7'

services:
  aqi-monitor-core:
    build:
      context: ./aqi_monitor
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    ports:
      - "5432:5432"
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aqi_index

volumes:
  postgres_data: