# Generated by Django 3.0.7 on 2020-07-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('region_ID', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, related_name='user_region_ID', to='monitor.Region')),
            ],
        ),
        migrations.CreateModel(
            name='AQI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PM25', models.IntegerField(max_length=30)),
                ('PM10', models.IntegerField(max_length=30)),
                ('NO2', models.IntegerField(max_length=30)),
                ('CO', models.IntegerField(max_length=30)),
                ('SO2', models.IntegerField(max_length=30)),
                ('Ozone', models.IntegerField(max_length=30)),
                ('final_index', models.IntegerField(max_length=30)),
                ('time', models.DateTimeField()),
                ('message', models.CharField(max_length=200)),
                ('region_ID', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, related_name='aqi_region_ID', to='monitor.Region')),
            ],
        ),
    ]
