# Generated by Django 3.0.7 on 2020-07-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aqi',
            old_name='CO',
            new_name='CO_index',
        ),
        migrations.RenameField(
            model_name='aqi',
            old_name='NO2',
            new_name='NO2_index',
        ),
        migrations.RenameField(
            model_name='aqi',
            old_name='Ozone',
            new_name='Ozone_index',
        ),
        migrations.RenameField(
            model_name='aqi',
            old_name='PM10',
            new_name='PM10_index',
        ),
        migrations.RenameField(
            model_name='aqi',
            old_name='PM25',
            new_name='PM25_index',
        ),
        migrations.RenameField(
            model_name='aqi',
            old_name='SO2',
            new_name='SO2_index',
        ),
        migrations.AlterField(
            model_name='aqi',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
