# Generated by Django 3.0.7 on 2020-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200706_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqi',
            name='CO_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='NO2_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='Ozone_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='PM10_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='PM25_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='SO2_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='final_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
